# Largest Dog Breed Dataset
### Kaggle submission by Liam Larsen

The 2016 dataset lists the type of dog license issued to owners located in 131 different zip codes in Pennsylvania.  For each license issued, the breed type, color, and name of the dog is specified.

Import Libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
sns.set(style="white", color_codes=True)

Import data set

In [3]:
data = pd.read_csv("2016.csv")

Verify data is loaded, confirm all rows were loaded.  The data provided under "Column Metrics" in Kaggle agrees with the result below; 27018 rows, 7 columns.

In [4]:
data.shape

(27018, 7)

View column headings and the first five rows of the dataset.  Or change the number of rows to view by enterings a number in ().

In [5]:
data.head()

,LicenseType,Breed,Color,DogName,OwnerZip,ExpYear,ValidDate
0,Dog Individual Spayed Female,GOLDENDOODLE,GOLD,TALLY,15227,2016,2/16/2016 14:55
1,Dog Senior Citizen or Disability Spayed Female,CHIHUAHUA,WHITE/BLACK/BROWN,CHALUPA,15120,2016,1/11/2016 15:23
2,Dog Individual Neutered Male,GER SHORTHAIR POINT,SPOTTED,JINX,15236,2016,12/22/2015 15:32
3,Dog Senior Citizen or Disability Female,BEAGLE,MULTI,JACKPINE JERUSALEM,15044,2016,12/17/2015 12:28
4,Dog Senior Citizen or Disability Female,BEAGLE,MULTI,JACKPINE JORDAN,15044,2016,12/17/2015 12:28

View the last five rows of the dataset.

In [8]:
data.tail()

,LicenseType,Breed,Color,DogName,OwnerZip,ExpYear,ValidDate
27013,Dog Individual Spayed Female,GER SHEPHERD,WHITE,GHOST,15218,2016,12/13/2016 11:16
27014,Dog Individual Neutered Male,ROTTWEILER MIX,BLACK/BROWN,BUCKEYE,15044,2016,12/13/2016 11:18
27015,Dog Individual Neutered Male,SIB HUSKY,BROWN,ROCCO,15146,2016,12/19/2016 9:58
27016,Dog Individual Spayed Female,MIXED,BROWN,ECHO,15237,2016,12/19/2016 10:06
27017,Dog Senior Lifetime Male,YORKSHIRE TERRIER,BLACK/TAN,SCRAPPY,15110,2016,12/23/2016 10:15

In [ ]:
Check the data type.

In [9]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
Sample one variable.

In [12]:
data["Breed"].value_counts()

MIXED                   2941
LABRADOR RETRIEVER      1787
LAB MIX                 1598
GER SHEPHERD             926
AM PIT BULL TERRIER      872
GOLDEN RETRIEVER         827
CHIHUAHUA                776
SHIH TZU                 754
TAG                      685
BEAGLE                   684
YORKSHIRE TERRIER        633
BOXER                    580
BEAGLE MIX               555
DACHSHUND                504
GER SHEPHERD MIX         445
AM PITT BULL MIX         338
POMERANIAN               327
PUG                      324
TERRIER MIX              302
MALTESE                  298
BICHON FRISE             267
YORKSHIRE TERR MIX       262
BOXER MIX                255
COCKER SPANIEL           253
ROTTWEILER               242
CHIHUAHUA MIX            238
GOLDENDOODLE             236
SIB HUSKY                226
SHETLAND SHEEPDOG        225
BOSTON TERRIER           201
                        ...
ENTLEBUCHER SENNEN         1
MULLINS FEIST              1
HALLS HEELER               1
BLACK RUSSIAN TERRI        1
KAI DOG                    1
Mountain Feist             1
WATER DOG SPANISH          1
POLISH LOWLND SHEEP        1
POLISH HOUND               1
CENT ASIA SHEPHARD         1
AFFENPINSCHER              1
SALUKI                     1
DENMARK FEIST              1
IRISH WATER SPANIEL        1
POLISH TATRA SHEEPDO       1
TIBETAN SPANIEL            1
DUNKER                     1
AUS KELPIE                 1
TOY FOX TERIER             1
SARPLANINAC                1
ENG TOY TERRIER            1
PYRENEAN MASTIFF           1
EURASIAN                   1
CURLY COATED RETRIE        1
MUNSTERLANDER LARGE        1
BELG SHEEPDOG              1
GER LONGHAIR POINT         1
DINGO                      1
GRIFFON NIVERNAIS          1
BEAUCERON                  1
Name: Breed, Length: 275, dtype: int64

In [ ]:
Column named "Breed" is set as the index column.

In [16]:
df1 = data.set_index('Breed')

df1

,LicenseType,Color,DogName,OwnerZip,ExpYear,ValidDate
Breed,,,,,,
GOLDENDOODLE,Dog Individual Spayed Female,GOLD,TALLY,15227,2016,2/16/2016 14:55
CHIHUAHUA,Dog Senior Citizen or Disability Spayed Female,WHITE/BLACK/BROWN,CHALUPA,15120,2016,1/11/2016 15:23
GER SHORTHAIR POINT,Dog Individual Neutered Male,SPOTTED,JINX,15236,2016,12/22/2015 15:32
BEAGLE,Dog Senior Citizen or Disability Female,MULTI,JACKPINE JERUSALEM,15044,2016,12/17/2015 12:28
BEAGLE,Dog Senior Citizen or Disability Female,MULTI,JACKPINE JORDAN,15044,2016,12/17/2015 12:28
W HGHLND WH TERRIER,Dog Individual Spayed Female,WHITE,JULI,15108,2016,12/9/2015 12:18
LAB MIX,Dog Individual Spayed Female,YELLOW,MIA,15133,2016,7/19/2016 14:41
DACHSHUND,Dog Individual Spayed Female,BLACK,SOPHIE,15108,2016,1/20/2016 9:03
ST BERNARD,Dog Individual Male,WHITE/BROWN,BOLU,15237,2016,12/3/2015 13:53
LABRADOR RETRIEVER,Dog Individual Spayed Female,BROWN,HERSHEY,15025,2016,2/9/2016 16:14
POODLE TOY,Dog Senior Citizen or Disability Spayed Female,BLACK,SASSY II,15101,2016,12/14/2015 15:42
MIXED,Dog Individual License Duplicate,TAN,CASI,15120,2016,10/13/2016 8:32
BOXER MIX,Dog Individual Neutered Male,SPOTTED,DUNCAN,15044,2016,6/15/2016 15:11
LABRADOR RETRIEVER,Dog Individual Male,BLACK,LUKE,15014,2016,2/16/2016 12:58
MALTESE,Dog Senior Citizen or Disability Male,WHITE,TED E BEAR,15148,2016,1/8/2016 8:30
LABRADOR RETRIEVER,Dog Individual Neutered Male,BLACK,JERSEY,15017,2016,1/26/2016 12:58
MIXED,Dog Senior Citizen or Disability Spayed Female,BLONDE,PUNKIN,15146,2016,11/20/2015 14:06
SHIH TZU,Dog Senior Citizen or Disability Neutered Male,BLACK/CREAM,LEO,15227,2016,3/14/2016 15:36
OLD ENG SHEEPDOG,Dog Senior Citizen or Disability Neutered Male,WHITE/GREY,MAX,15129,2016,12/7/2015 12:36
SHETLAND SHEEPDOG,Dog Senior Citizen or Disability Spayed Female,MULTI,SABLE,15237,2016,12/17/2015 9:10
GORDON SETTER,Dog Senior Citizen or Disability Spayed Female,BLACK,GILLIE,15143,2016,1/13/2016 11:35
TERRIER MIX,Dog Individual Spayed Female,BLACK/RED,JESSICA,15136,2016,2/17/2016 15:15
MIXED,Dog Senior Citizen or Disability Spayed Female,WHITE/BLACK,RAKEISHA,15025,2016,12/21/2015 15:33
CHIHUAHUA MIX,Dog Senior Citizen or Disability Spayed Female,WHITE/TAN,ZEEBA,15025,2016,12/21/2015 15:33
COCKER SPANIEL MIX,Dog Individual Neutered Male,WHITE,GUNTHER,15243,2016,1/13/2016 9:17
GER SHEPHERD MIX,Dog Individual Neutered Male,BRINDLE,LUIGI,15017,2016,12/28/2015 16:00
YORKSHIRE TERR MIX,Dog Individual Spayed Female,BLACK,HALEY,15065,2016,11/30/2015 16:16
YORKSHIRE TERR MIX,Dog Individual Neutered Male,BLACK,BLAKE,15065,2016,11/30/2015 16:16
MIXED,Dog Individual Spayed Female,WHITE/TAN,BUNNY,15144,2016,3/11/2016 9:32
BORD COLLIE,Dog Individual Spayed Female,GREY,NORA,15220,2016,1/8/2016 9:07
...,...,...,...,...,...,...
MIXED,Dog Individual Male,BROWN,BUDDY,15239,2016,11/15/2016 14:48
BICHON FRISE,Dog Individual Female,WHITE,MOLLYSUE,15235,2016,11/15/2016 15:28
GER SHEPHERD,Dog Individual Neutered Male,BLACK/BROWN,MAX,15214,2016,11/15/2016 15:30
SIB HUSKY MIX,Dog Individual Female,SPOTTED,ELLA,15071,2016,11/16/2016 9:54
YORKSHIRE TERRIER,Dog Individual Neutered Male,BLACK/BROWN,SID,15237,2016,11/16/2016 9:31
BOXER,Dog Individual Male,FAWN,ZADOR,15235,2016,11/16/2016 10:47
BORD COLLIE,Dog Individual Male,WHITE/BLACK,ROGUE,15147,2016,11/16/2016 11:21
BRITTANY SPANIEL,Dog Individual Male,WHITE/LIVER,CHAOS,15147,2016,11/16/2016 11:21
BORD COLLIE,Dog Individual Male,WHITE/BLACK,HAVOK,15147,2016,11/16/2016 11:21
WEIMARANER,Dog Individual Spayed Female,GREY,HEIDI,15202,2016,11/16/2016 14:05
LAB MIX,Dog Individual Spayed Female,WHITE/BLACK,SHAWNEE,15202,2016,11/16/2016 14:31
MIXED,Dog Individual Male,BROWN,DUKE,15202,2016,11/17/2016 11:00
POODLE MIX,Dog Out of County Transfer - Senior,BLONDE,SAMMY,15057,2016,11/17/2016 12:14
SHIH TZU,Dog Individual Spayed Female,GREY,SWEETIE,15202,2016,11/18/2016 11:45
TERRIER MIX,Dog Individual Spayed Female,BLACK,PRNICESS,15223,2016,11/18/2016 14:13
AM PIT BULL TERRIER,Dog Individual Female,BLACK,MINNEI,15132,2016,11/21/2016 9:26
AM PIT BULL TERRIER,Dog Individual Neutered Male,BROWN,ASLAN,15209,2016,11/22/2016 9:15
GER SHEPHERD,Dog Individual Male,BLACK/BROWN,KODI,15136,2016,11/22/2016 14:41
AUS SHEPHERD,Dog Senior Citizen or Disability Neutered Male,WHITE/BLACK/BROWN,DOJO,15236,2016,11/23/2016 16:29
TAG,Dog Individual Spayed Female,TAN,HECTOR,15044,2016,11/25/2016 9:23
CHINESE CRESTED,Dog Senior Citizen or Disability Neutered Male,SPOTTED,HARRY,15227,2016,11/25/2016 10:03
FRENCH BULLDOG,Dog Senior Citizen or Disability Spayed Female,BLACK,DOLLY,15142,2016,11/28/2016 15:52
BOXER,Dog Individual Male,BROWN,DEXTER,15241,2016,11/30/2016 11:54
GOLDEN RETRIEVER,Dog Individual Neutered Male,GOLD,REILLY,15227,2016,12/5/2016 11:53
BOXER,Dog Individual Male,SPOTTED,BRUTUS,15108,2016,12/6/2016 10:24
GER SHEPHERD,Dog Individual Spayed Female,WHITE,GHOST,15218,2016,12/13/2016 11:16
ROTTWEILER MIX,Dog Individual Neutered Male,BLACK/BROWN,BUCKEYE,15044,2016,12/13/2016 11:18
SIB HUSKY,Dog Individual Neutered Male,BROWN,ROCCO,15146,2016,12/19/2016 9:58
MIXED,Dog Individual Spayed Female,BROWN,ECHO,15237,2016,12/19/2016 10:06
YORKSHIRE TERRIER,Dog Senior Lifetime Male,BLACK/TAN,SCRAPPY,15110,2016,12/23/2016 10:15

In [ ]:
Group by and compute the sum.        >>>>FIGURE OUT HOW TO DO THIS WITH COUNT - 1 per row!  It only pulled in the columns w/ #.

In [18]:
df2 = df1.groupby('Breed').sum()

df2

                     OwnerZip  ExpYear
Breed
.                      408888    54432
AFFENPINSCHER           15228     2016
AFGHAN HOUND            15209     2016
AIREDALE TERRIER       652627    86688
AKITA                  332941    44352
AKITA MIX              136636    18144
ALAPAHA BLUE BULLDO     30237     4032
ALAS KLEE KAI           30322     4032
ALAS MALAMUTE          440077    58464
ALPINE MASTIFF          30317     4032
AM BLACK&TAN COONHO     60701     8064
AM BULLDOG            2135958   284256
AM ESKIMO DOG          954979   127008
AM FOXHOUND            182124    24192
AM PIT BULL TERRIER  13208380  1757952
AM PITT BULL MIX      5120170   681408
AM STAFF TERRIER       786953   104832
AM TOY TERRIER         120965    16128
AM WATER SPANIEL        75343    10080
ANATOLIAN SHEPHERD      45700     6048
ARGENTINO DOGO          30378     4032
AUS CATTLE DOG        1091779   145152
AUS KELPIE              15227     2016
AUS SHEPHERD          2516137   334656
AUS TERRIER             30370     4032
BARBET                  30482     4032
BASENJI                197105    26208
BASSET HOUND          1515287   201600
BASSET HOUND MIX       272974    36288
BEAGLE               10363981  1378944
...                       ...      ...
SHIH TZU MIX          2438352   324576
SHILOH GER SHEPHERD     45430     6048
SIB HUSKY             3428610   455616
SIB HUSKY MIX         1528670   203616
SILKY TERRIER          363701    48384
SKYE TERRIER            15084     2016
SPINONE ITALIANO        60390     8064
ST BERNARD            1271624   169344
STABYHOUN               15228     2016
STAFFORDSHIRE TERRI    136101    18144
TAG                  10378346  1380960
TEDDY ROOSE TERRIER     75853    10080
TERRIER               1392814   185472
TERRIER MIX           4576652   608832
TIBETAN SPANIEL         15229     2016
TIBETAN TERRIER        243208    32256
TOY FOX TERIER          15221     2016
TREE WALK COONHOUND    257670    34272
VIZSLA                 802343   106848
W HGHLND WH TERRIER   2440637   324576
WATER DOG SPANISH       15090     2016
WEIMARANER            1333595   177408
WELSH CORGI CARDIGA    515074    68544
WELSH CORGI PEMBROK   1440032   191520
WELSH SPRINGER SPAN     45556     6048
WELSH TERRIER          136712    18144
WHIPPET                378677    50400
WIREHAIR PT GRIFFON     90622    12096
YORKSHIRE TERR MIX    3967721   528192
YORKSHIRE TERRIER     9589789  1276128

[275 rows x 2 columns]